from app import db

class NewTable(db.Model):
    __tablename__ = 'newtable'
    id = db.Column(db.Integer,primary_key=True,nullable=True)
    tid = db.Column(db.String(48),index=True,nullable=True,unique=True)
    creator = db.Column(db.String(48), nullable=True)
    model_name = db.Column(db.String(48), nullable=True, unique=True)
    table_data = db.Column(db.String(2000))
    merge_cells = db.Column(db.String(2000))
    step_data = db.Column(db.String(2000))
    step_order = db.Column(db.String(2000))
    explain = db.Column(db.String(2000))
    other_data = db.Column(db.String(2000))
    remarks = db.Column(db.String(2000))
    html_code = db.Column(db.String(2000))
    create_time = db.Column(db.DateTime)
    spare1 = db.Column(db.String(48))
    spare2 = db.Column(db.String(48))
    spare3 = db.Column(db.String(48))

class NewTable_Rule(db.Model):
    __tablename__ = 'newtablerule'
    id = db.Column(db.Integer,primary_key=True,nullable=True)
    tid = db.Column(db.String(48),index=True,nullable=True,unique=True)
    creator = db.Column(db.String(48), nullable=True)
    model_name = db.Column(db.String(48), nullable=True, unique=True)
    table_data = db.Column(db.String(2000))
    merge_cells = db.Column(db.String(2000))
    step_data = db.Column(db.String(2000))
    step_order = db.Column(db.String(2000))
    explain = db.Column(db.String(2000))
    other_data = db.Column(db.String(2000))
    remarks = db.Column(db.String(2000))
    html_code = db.Column(db.String(2000))
    base_model = db.Column(db.String(2000))
    table_rule = db.Column(db.String(3000))
    create_time = db.Column(db.DateTime)
    spare1 = db.Column(db.String(48))
    spare2 = db.Column(db.String(48))
    spare3 = db.Column(db.String(48))

class NewTable_End(db.Model):
    __tablename__ = 'newtableend'
    id = db.Column(db.Integer,primary_key=True,nullable=True)
    tid = db.Column(db.String(48),index=True,nullable=True,unique=True)
    creator = db.Column(db.String(48), nullable=True)
    model_name = db.Column(db.String(48), nullable=True, unique=True)
    table_data = db.Column(db.String(2000))
    merge_cells = db.Column(db.String(2000))
    step_data = db.Column(db.String(2000))
    step_order = db.Column(db.String(2000))
    explain = db.Column(db.String(2000))
    other_data = db.Column(db.String(1000))
    remarks = db.Column(db.String(1000))
    html_code = db.Column(db.String(2000))
    base_model = db.Column(db.String(2000))
    table_rule = db.Column(db.String(3000))
    create_time = db.Column(db.DateTime)
    data = db.Column(db.String(2000))
    spare2 = db.Column(db.String(48))
    spare3 = db.Column(db.String(48))